# path to the task data directory
data_dir: null
dataset_dir: null

# either provide a path to a plaintext file describing the task
desc_file: null
# or provide the task goal (and optionally evaluation information) as arguments
goal: null
eval: null

log_dir: ./logs/run
log_level: INFO
workspace_dir: ./workspaces/run

# whether to unzip any archives in the data directory
preprocess_data: True
# whether to copy the data to the workspace directory (otherwise it will be symlinked)
# copying is recommended to prevent the agent from accidentally modifying the original data
copy_data: False

exp_name: null # a random experiment name will be generated if not provided

# settings for code execution
exec:
  timeout: 32400
  agent_file_name: runfile.py
  format_tb_ipython: False

# agent hyperparams
agent:
  # how many improvement iterations to run
  steps: 500
  # total time available to agent
  time_limit: 43200 # 12 hrs (purely informational, implementation is user's resp)
  # whether to instruct the agent to use CV (set to 1 to disable)
  k_fold_validation: 1
  # whether to instruct the agent to generate a prediction function
  expose_prediction: False
  # whether to provide the agent with a preview of the data
  data_preview: True
  # whether to convert system messages into user messages
  convert_system_to_user: False
  # whether to obfuscate that we're doing kaggle
  obfuscate: False
  # check submission format
  check_format: True
  # for mcts
  save_all_submission: True
  # steerable reasoning, only works when your deepseek api support client.completions.create()
  steerable_reasoning: False 

  # LLM settings for coding
  code:
    model: deepseek-r1
    temp: 0.5
    base_url: "your_deepseek_url"
    api_key: "your_deepseek_url"

  # LLM settings for evaluating program output / tracebacks
  feedback:
    model: gpt-4o-2024-08-06
    temp: 0.5
    base_url: "your_gpt_url"
    api_key: "your_gpt_api_key"

  # hyperparameters for the tree search
  search:
    back_debug_depth: 3
    max_debug_depth: 20
    debug_prob: 1
    num_drafts: 5
    num_bugs: 1
    num_improves: 3
    invalid_metric_upper_bound: 100
    metric_improvement_threshold: 0.0001
    max_improve_failure: 3
    parallel_search_num: 3
  
  decay:
    decay_type: piecewise       # decay_type
    exploration_constant: 1.414        # exploration constant
    lower_bound: 0.5                   # Lower exploration limit to prevent values from being too small
    linear_decay:
      alpha: 0.01
    exponential_decay:
      gamma: 0.99
    piecewise_decay:
      alpha: 0.01
      phase_ratios: [0.3, 0.7]
    dynamic_piecewise_decay:
      alpha: 0.01
      phase_ratios: [0.85, 1]
    




